FROM cypress/base as builder

ENV VUE_APP_BASE_URL=/
ENV VUE_APP_RESTAPI_URL=/api-gateway/v1

WORKDIR /app

COPY package.json /app/
COPY .npmrc /app/
COPY package-lock.json /app/

RUN npm ci

COPY ./ /app/

RUN npm run test:unit
RUN npm run test:e2e

RUN npm run build

FROM bitnami/nginx:latest

COPY --from=builder /app/nginx.dev.conf /opt/bitnami/nginx/conf/vhosts/default.conf
COPY --from=builder /app/dist/ /app/dist/
